require("user.options")
require("user.keymaps").main()
require("user.autocmds")
require("user.plugins")
require("user.settings").setup()
require("user.lsp")
require("user.treesitter")
require("user.comment")
require("user.cmp")
require("user.null_ls")
require("user.others")
require("user.tabline")
require("user.statusline")
require("user.gitsigns")
require("user.neotree")
require("user.colorscheme")
require("user.telescope")

-- vim.cmd("colorscheme minimal")
